---
- hosts: all
  become: yes

  tasks:
    - name: Install prerequistes
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Mysql server
      apt:
       name:
       - mysql-server
       - python3-pymysql
       - mysql-client
       - python3-mysqldb
       - libmysqlclient-dev

    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow  

    - name: "UFW - Allow Mysql on port 3306"
      ufw:
        rule: allow
        port: "3306"
        proto: tcp

    - name: Allow port 80
      ufw:
        rule: limit
        port: "80"
        proto: tcp
    

    - name: Enable remote login to mysql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql

    - name: Enable remote login to mysql db
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^mysqlx-bind-address'
        line: 'mysqlx-bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql

    # - name: Enable remote login to mysql
    #   lineinfile:
    #     path: /etc/mysql/mysql.conf.d/mysqld.cnf
    #     regexp: '^mysqlx-bind-address'
    #     line: 'mysqlx-bind-address = 0.0.0.0'
    #     backup: yes
    #   notify:
    #     - Restart mysql

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: creating mysql user admin
      mysql_user:
        name: "admin"
        password: "password"
        priv: '*.*:ALL'
        host: '192.168.50.4'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Fiifi db
      mysql_db:
        name: "Fiifi"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock




  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted

        # name: Run mysql query
        # community.mysql.mysql_user: 
        #   user:
        #   - CREATE USER 'admin'@'192.168.50.4' identified by 'password';
        #   - GRANT ALL PRIVILEGES ON *.* TO 'admin'@'192.168.50.4';
        #   - FLUSH PRIVILEGES;   
        #   - CREATE DATABASE fbs;