---
- hosts: all
  become: true

  tasks:
  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - php
      # - mcrypt
      # - nginx
      # - php5-cli
      # - php5-curl
      # - php5-fpm
      # - php5-intl
      # - php5-json
      # - php5-mcrypt
      # - php5-sqlite
      # - sqlite3