---
- hosts: app
  become: true

  tasks:
    - name: Update apt-get repo and cache
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600

    - name: Install prerequistes
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Mysql server
      apt:
       name:
       - mysql-server
       - python3-pymysql
       - mysql-client
       - python3-mysqldb
       - libmysqlclient-dev

 
    - name: Ensure apache2 is present
      apt: 
        name: apache2
        state: present


    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow

    - community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        name: 'Apache'
           
    
