---
- hosts: app
  become: true

  tasks:
    - name: Update apt-get repo and cache
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600

    - name: Install prerequistes
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Mysql server
      apt:
       name:
       - mysql-server
       - python3-pymysql
       - mysql-client
       - python3-mysqldb
       - libmysqlclient-dev

    # - name: Upgrade all apt packages
    #   apt: 
    #     upgrade: dist 
    #     force_apt_get: yes
 
    - name: Ensure apache2 is present
      apt: 
        name: apache2
        state: present


    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow

    # - name: Set logging
    #   community.general.ufw:
    #     logging: 'on' 
   
    # - community.general.ufw:
    #     rule: reject
    #     port: auth
    #     log: yes

    - community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    # # - name: Delete OpenSSH rule
    # #   community.general.ufw:
    # #     rule: allow
    # #     name: OpenSSH
    # #     delete: yes

    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        name: 'Apache'
           
    # # - name: Uncomment configuration
    # #   replace:
    # #     path: /etc/ansible/ansible.cfg
    # #     regexp: '#(\s+)host_key_checking'
    # #     replace: 'host_key_checking'
    # #     backup: yes

    # - name: Copy file with owner and permission
    #   ansible.builtin.copy:
    #     src: /vagrant/hosts
    #     dest: /etc/ansible/hosts
    #     owner: root
    #     group: root
    #     mode: 0644
    